/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Controlador.ControladorPrincipal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Controlador.ControladorInicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Tapsin
 */
public class JPInicio extends javax.swing.JPanel {
 
    public ControladorInicio control;
    /** Creates new form jPInicio */
    public JPInicio(ControladorInicio control) {
        this.control = control;
        try {
// apariencia del SO
            UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }   
        initComponents();
    }
        public void alerta(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "¡Advertencia!", JOptionPane.WARNING_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelAutor = new javax.swing.JLabel();
        LogoUsach = new javax.swing.JLabel();
        LabelInstruccion = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(proyectodetitulo.ProyectoDeTituloApp.class).getContext().getResourceMap(JPInicio.class);
        LabelTitulo.setFont(resourceMap.getFont("LabelTitulo.font")); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText(resourceMap.getString("LabelTitulo.text")); // NOI18N
        LabelTitulo.setName("LabelTitulo"); // NOI18N

        LabelAutor.setFont(resourceMap.getFont("LabelAutor.font")); // NOI18N
        LabelAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelAutor.setText(resourceMap.getString("LabelAutor.text")); // NOI18N
        LabelAutor.setName("LabelAutor"); // NOI18N

        LogoUsach.setIcon(resourceMap.getIcon("LogoUsach.icon")); // NOI18N
        LogoUsach.setName("LogoUsach"); // NOI18N

        LabelInstruccion.setText(resourceMap.getString("LabelInstruccion.text")); // NOI18N
        LabelInstruccion.setName("LabelInstruccion"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoUsach)
                    .addComponent(LabelAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(LabelInstruccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoUsach, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAutor;
    private javax.swing.JLabel LabelInstruccion;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LogoUsach;
    // End of variables declaration//GEN-END:variables

}
